;;; xkcd-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from xkcd.el

(autoload 'xkcd-mode "xkcd" "\
Major mode for viewing xkcd (https://xkcd.com/) comics.

(fn)" t)
(autoload 'xkcd-get "xkcd" "\
Get the xkcd number NUM.

(fn NUM)" t)
(autoload 'xkcd-get-latest "xkcd" "\
Get the latest xkcd." t)
(defalias 'xkcd 'xkcd-get-latest)
(register-definition-prefixes "xkcd" '("get-xkcd-from-url" "xkcd-"))

;;; End of scraped data

(provide 'xkcd-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; xkcd-autoloads.el ends here
